import { Navigation } from "@/components/Navigation";
import { Hero } from "@/components/Hero";
import { FeatureCard } from "@/components/FeatureCard";
import { Button } from "@/components/ui/button";
import { 
  Brain, 
  Trophy, 
  Zap, 
  Target, 
  BookOpen, 
  Award,
  ArrowRight,
  CheckCircle 
} from "lucide-react";
import roadmapImage from "@/assets/roadmap-illustration.jpg";

const Index = () => {
  return (
    <div className="min-h-screen bg-background">
      {/* Navigation */}
      <Navigation />

      {/* Hero Section */}
      <Hero />

      {/* Features Section */}
      <section id="features" className="py-20 bg-background">
        <div className="container mx-auto px-4">
          <div className="text-center mb-16">
            <h2 className="text-4xl md:text-5xl font-bold mb-6">
              Why Choose <span className="bg-gradient-primary bg-clip-text text-transparent">AdaptLearn</span>?
            </h2>
            <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
              Experience the future of personalized education with AI-powered learning paths.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            <FeatureCard
              icon={Brain}
              title="AI-Powered Roadmaps"
              description="Get personalized learning paths generated by advanced AI based on your goals and available time."
            />
            <FeatureCard
              icon={Target}
              title="Milestone Tracking"
              description="Progress through structured milestones with clear objectives and measurable outcomes."
            />
            <FeatureCard
              icon={Zap}
              title="Interactive Quizzes"
              description="Test your knowledge with engaging quizzes that unlock the next stage of your journey."
            />
            <FeatureCard
              icon={Trophy}
              title="Achievement System"
              description="Earn badges and certificates as you complete courses and reach new milestones."
            />
            <FeatureCard
              icon={BookOpen}
              title="Curated Resources"
              description="Access high-quality resources including videos, articles, and interactive content."
            />
            <FeatureCard
              icon={Award}
              title="Certificates"
              description="Download professional certificates upon course completion to showcase your skills."
            />
          </div>
        </div>
      </section>

      {/* How it Works Section */}
      <section id="how-it-works" className="py-20 bg-card/30">
        <div className="container mx-auto px-4">
          <div className="text-center mb-16">
            <h2 className="text-4xl md:text-5xl font-bold mb-6">
              How It <span className="bg-gradient-primary bg-clip-text text-transparent">Works</span>
            </h2>
            <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
              Simple steps to start your personalized learning journey.
            </p>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
            <div className="space-y-8">
              <div className="flex items-start gap-4">
                <div className="w-10 h-10 bg-gradient-primary rounded-full flex items-center justify-center text-primary-foreground font-bold text-lg">
                  1
                </div>
                <div>
                  <h3 className="text-xl font-semibold mb-2">Tell Us Your Goals</h3>
                  <p className="text-muted-foreground">
                    Share what you want to learn and how much time you have available.
                  </p>
                </div>
              </div>

              <div className="flex items-start gap-4">
                <div className="w-10 h-10 bg-gradient-primary rounded-full flex items-center justify-center text-primary-foreground font-bold text-lg">
                  2
                </div>
                <div>
                  <h3 className="text-xl font-semibold mb-2">Get Your Roadmap</h3>
                  <p className="text-muted-foreground">
                    AI generates a personalized learning path with milestones and resources.
                  </p>
                </div>
              </div>

              <div className="flex items-start gap-4">
                <div className="w-10 h-10 bg-gradient-primary rounded-full flex items-center justify-center text-primary-foreground font-bold text-lg">
                  3
                </div>
                <div>
                  <h3 className="text-xl font-semibold mb-2">Learn & Progress</h3>
                  <p className="text-muted-foreground">
                    Complete milestones, pass quizzes, and track your progress.
                  </p>
                </div>
              </div>

              <div className="flex items-start gap-4">
                <div className="w-10 h-10 bg-gradient-primary rounded-full flex items-center justify-center text-primary-foreground font-bold text-lg">
                  4
                </div>
                <div>
                  <h3 className="text-xl font-semibold mb-2">Earn Certificates</h3>
                  <p className="text-muted-foreground">
                    Get certificates and discover your next learning adventure.
                  </p>
                </div>
              </div>
            </div>

            <div className="relative">
              <img
                src={roadmapImage}
                alt="Learning roadmap visualization"
                className="w-full rounded-2xl shadow-2xl"
              />
              <div className="absolute inset-0 bg-gradient-primary/10 rounded-2xl" />
            </div>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 bg-gradient-hero relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-hero/80" />
        <div className="container mx-auto px-4 text-center relative z-10">
          <h2 className="text-4xl md:text-5xl font-bold mb-6 text-foreground">
            Ready to Start Your Learning Journey?
          </h2>
          <p className="text-xl text-foreground/80 mb-8 max-w-2xl mx-auto">
            Join thousands of learners who are already achieving their goals with personalized AI-powered education.
          </p>
          <Button 
            variant="hero" 
            size="xl" 
            className="bg-background text-foreground hover:bg-background/90"
            onClick={() => window.location.href = '/auth'}
          >
            Get Started Now
            <ArrowRight className="ml-2 h-5 w-5" />
          </Button>
        </div>
      </section>

      {/* Footer */}
      <footer className="py-12 bg-background border-t border-border">
        <div className="container mx-auto px-4 text-center">
          <p className="text-muted-foreground">
            © 2024 AdaptLearn. Empowering learners with AI-driven education.
          </p>
        </div>
      </footer>
    </div>
  );
};

export default Index;
