// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://icwcxsdipybqaizbovnp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imljd2N4c2RpcHlicWFpemJvdm5wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyMzExMDksImV4cCI6MjA3MjgwNzEwOX0.xp4lo_p8ZZs0u2VLYXJXDmzLSZYCcQktZklQKzPcuqc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});